apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratings-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - name: ratings
        image: anthonyamanse/ratings-v1
        imagePullPolicy: Always
        env:
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: password
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: host
          - name: MYSQL_DB_PORT
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: port
        ports:
        - containerPort: 9080
