apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: journeycode/reviews-v1
        imagePullPolicy: Always
        env:
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: password
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: host
          - name: MYSQL_DB_PORT
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: port
        ports:
        - containerPort: 9080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: journeycode/reviews-v2
        imagePullPolicy: Always
        env:
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: password
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: host
          - name: MYSQL_DB_PORT
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: port
        ports:
        - containerPort: 9080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews
        image: journeycode/reviews-v3
        imagePullPolicy: Always
        env:
          - name: MYSQL_DB_USER
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: password
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: host
          - name: MYSQL_DB_PORT
            valueFrom:
              secretKeyRef:
                name: demo-credentials
                key: port
        ports:
        - containerPort: 9080
